from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from .views import (
    echarts_members,
    file_delete,
    file_delete_batch,
    file_page,
    file_update,
    file_upload,
    get_data,
    login_test,
    menu_delete,
    menu_delete_batch,
    menu_entry,
    menu_icons,
    menu_ids,
    menu_list,
    menu_save,
    role_delete,
    role_delete_batch,
    role_entry,
    role_list,
    role_role_menu_entry,
    role_page,
    role_role_menu,
    role_role_menu_save,
    role_save,
    user_by_username,
    user_delete,
    user_delete_batch,
    user_login,
    user_page,
    user_register,
    user_update_password,
    user_save,
)
 
urlpatterns = [
    path('api/data/', get_data, name='get_data'),
    path('api/login-test/', login_test, name='login_test'),
    path('api/', include('BackEnd.generated_api.urls')),
    path('user/login', user_login),
    path('user/register', user_register),
    path('user/username/<str:username>', user_by_username),
    path('user/page', user_page),
    path('user', user_save),
    path('user/updatePassword', user_update_password),
    path('user/<int:user_id>', user_delete),
    path('user/deleteBatch', user_delete_batch),
    path('role', role_entry),
    path('role/page', role_page),
    path('role/<int:role_id>', role_delete),
    path('role/deleteBatch', role_delete_batch),
    path('role/roleMenu/<int:role_id>', role_role_menu_entry),
    path('menu', menu_entry),
    path('menu/icons', menu_icons),
    path('menu/ids', menu_ids),
    path('menu/<int:menu_id>', menu_delete),
    path('menu/deleteBatch', menu_delete_batch),
    path('file/page', file_page),
    path('file/<int:file_id>', file_delete),
    path('file/deleteBatch', file_delete_batch),
    path('file/update', file_update),
    path('file/upload', file_upload),
    path('echarts/members', echarts_members),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)