from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path
from .views import (
    echarts_members,
    import_data,
    import_datasets_all,
    import_file,
    file_delete,
    file_delete_batch,
    file_page,
    file_update,
    upload_file,
    get_data,
    login_test,
    menu_delete,
    menu_delete_batch,
    menu_entry,
    menu_icons,
    menu_ids,
    menu_list,
    menu_save,
    role_delete,
    role_delete_batch,
    role_entry,
    role_list,
    role_role_menu_entry,
    role_page,
    role_role_menu,
    role_role_menu_save,
    role_save,
    user_by_username,
    user_delete,
    user_delete_batch,
    user_login,
    user_page,
    user_register,
    user_update_password,
    user_save,
    upload_template,
)
from BackEnd.analysis.api import (
    analyze_track_workload,
    analyze_all_tracks_workload,
    get_workload_summary_view,
)
from BackEnd.views_frontend import serve_frontend
 
urlpatterns = [
    path('api/data/', get_data, name='get_data'),
    path('api/login-test/', login_test, name='login_test'),
    path('api/upload-file/', upload_file, name='upload_file'),
    path('api/import-file/', import_file, name='import_file'),
    path('api/import-data/', import_data, name='import_data'),
    path('api/import-datasets-all/', import_datasets_all, name='import_datasets_all'),
    path('api/upload-template/', upload_template, name='upload_template'),
    path('api/', include('BackEnd.generated_api.urls')),
    # 农机作业量统计分析API
    path('api/analysis/track/<int:track_id>/', analyze_track_workload, name='analyze_track_workload'),
    path('api/analysis/all-tracks/', analyze_all_tracks_workload, name='analyze_all_tracks_workload'),
    path('api/analysis/summary/', get_workload_summary_view, name='get_workload_summary'),
    path('user/login', user_login),
    path('user/register', user_register),
    path('user/username/<str:username>', user_by_username),
    path('user/page', user_page),
    path('user', user_save),
    path('user/updatePassword', user_update_password),
    path('user/<int:user_id>', user_delete),
    path('user/deleteBatch', user_delete_batch),
    path('role', role_entry),
    path('role/page', role_page),
    path('role/<int:role_id>', role_delete),
    path('role/deleteBatch', role_delete_batch),
    path('role/roleMenu/<int:role_id>', role_role_menu_entry),
    path('menu', menu_entry),
    path('menu/icons', menu_icons),
    path('menu/ids', menu_ids),
    path('menu/<int:menu_id>', menu_delete),
    path('menu/deleteBatch', menu_delete_batch),
    path('file/page', file_page),
    path('file/<int:file_id>', file_delete),
    path('file/deleteBatch', file_delete_batch),
    path('file/update', file_update),
    path('file/upload', upload_file),
    path('echarts/members', echarts_members),
    # Vue3 SPA — 放在最后，作为兜底路由
    re_path(r'^(?!api/|images/|datasets/|static/|user/|role/|menu/|file/|echarts/).*$', serve_frontend),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.DATASETS_URL, document_root=settings.DATASETS_ROOT)